version: '3'
services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/log:/var/log/nginx/"
      - "./nginx/report:/etc/nginx/report"
      - "/etc/letsencrypt:/etc/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
      - "8090:8090"
