version: '3'

services:
    python:
        build: ./
        container_name: test
        volumes:
          - ./test:/usr/src/app
        ports:
          - 5000:5000
        command: python3 app.py

    redis:
        image: redis:alpine

